version: '3'

services:
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-api:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/images:/code/images:rw
    networks:
      - backend_network  

networks:
  backend_network:
    name: backend_network
    external: true
